name: mind_snack

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.3
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.2
  maze: ^3.0.0
  sudoku_dart: ^1.2.0
  crossword_generator: ^1.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/